name: Build and Publish Docker Image

on:
  release:
    types:
      - created

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build JAR
        run: |
          javac -cp ./libs/*.jar -d . ./src/**/*.java
          jar cmf ./src/META-INF/MANIFEST.MF ./game.jar -C . ./src

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: game-jar
          path: ./game.jar

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            starloco/login:latest
            starloco/login:${{ steps.vars.outputs.tag }}

      - name: Docker Hub Description (README.md)
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/login
          readme-filepath: README.md